import browser from 'webextension-polyfill';
import css from './styles.css?inline';
import type {ScanState} from './types';
const flag='__cyberlensShieldLoaded';const global=window as unknown as Record<string,unknown>;
if(!global[flag]){global[flag]=true;
 let warning:HTMLElement|undefined,proceeded:string|undefined,linkEnabled=false,count=0,flush:ReturnType<typeof setTimeout>|undefined;const pending=new Map<string,HTMLAnchorElement[]>(),seen=new Set<string>();
 function element<K extends keyof HTMLElementTagNameMap>(tag:K,text='',className=''){const node=document.createElement(tag);node.textContent=text;node.className=className;return node;}
 function show(state:ScanState,url:string){if(url!==location.href||proceeded===url)return;warning?.remove();if(state.status!=='ready'||state.result.verdict==='SAFE')return;
  const dangerous=state.result.verdict==='DANGEROUS';const host=element('div');host.id='cyberlens-shield-warning';host.style.cssText='position:fixed;inset:'+(dangerous?'0':'16px 16px auto auto')+';z-index:2147483647;pointer-events:auto;';const shadow=host.attachShadow({mode:'open'});const style=element('style',css);shadow.append(style);const container=element('section','','font-sans text-slate-100 '+(dangerous?'flex h-screen w-screen items-center justify-center bg-slate-950/95 p-6':'w-80 rounded-2xl border border-amber-400/30 bg-slate-950 p-5 shadow-2xl'));container.setAttribute('role',dangerous?'alertdialog':'alert');container.setAttribute('aria-label','CyberLens Shield warning');if(dangerous)container.setAttribute('aria-modal','true');const card=element('div','','max-w-lg');const title=element('h2',dangerous?'Stop. This URL has dangerous signals.':'CyberLens: suspicious URL',dangerous?'text-xl font-semibold text-red-300':'text-sm font-semibold text-amber-200');card.append(title,element('p','CyberLens Shield · Risk '+state.result.score+'/100','mt-3 font-mono text-xs text-slate-400'));const list=element('ul','','my-4 space-y-2 text-sm leading-6');for(const reason of state.result.reasons.slice(0,5))list.append(element('li','• '+reason));card.append(list);const buttons=element('div','','flex flex-wrap gap-3');
  function dismiss(){host.remove();warning=undefined;proceeded=url;}
  if(dangerous){const back=element('button','Go back','btn');back.addEventListener('click',()=>{if(history.length>1)history.back();else location.replace('about:blank');});buttons.append(back);const proceed=element('button','Proceed anyway','btn secondary');proceed.addEventListener('click',dismiss);buttons.append(proceed);container.addEventListener('keydown',event=>{if(event.key==='Tab'){event.preventDefault();(shadow.activeElement===back?proceed:back).focus();}});setTimeout(()=>back.focus(),0);}else{const dismissButton=element('button','Dismiss warning','btn secondary');dismissButton.addEventListener('click',dismiss);buttons.append(dismissButton);}card.append(buttons);container.append(card);shadow.append(container);document.documentElement.append(host);warning=host;
 }
 async function sendBatch(){const entries=[...pending.entries()].slice(0,4);for(const [url] of entries)pending.delete(url);if(pending.size)flush=setTimeout(()=>void sendBatch(),600);if(!entries.length)return;try{const results=await browser.runtime.sendMessage({type:'SCAN_LINKS',urls:entries.map(([url])=>url)}) as {hash:string;state:ScanState}[];for(const [url,anchors] of entries){const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(url)))).map(v=>v.toString(16).padStart(2,'0')).join('');const result=results.find(item=>item.hash===hash);if(result?.state.status==='ready'&&result.state.result.verdict!=='SAFE')for(const anchor of anchors){if(!anchor.isConnected)continue;const icon=element('span',' ⚠','');icon.setAttribute('aria-label','CyberLens flagged this link as '+result.state.result.verdict.toLowerCase());icon.title=icon.getAttribute('aria-label')!;icon.style.cssText='display:inline;color:#fbbf24;font-size:14px;';anchor.after(icon);}}}catch{/* No risky annotation is invented when offline. */}}
 document.addEventListener('pointerover',event=>{if(!linkEnabled||count>=20)return;const target=event.target instanceof Element?event.target.closest('a[href]'):null;if(!(target instanceof HTMLAnchorElement)||!/^https?:/.test(target.href)||seen.has(target.href)||target.href.length>2048)return;seen.add(target.href);count++;pending.set(target.href,[target]);clearTimeout(flush);flush=setTimeout(()=>void sendBatch(),400);},{passive:true});
 browser.runtime.onMessage.addListener((message:unknown)=>{const data=message as {type:string;state:ScanState;url:string;linkScanning:boolean};if(data.type==='PAGE_RESULT'){linkEnabled=data.linkScanning;show(data.state,data.url);}return undefined;});
 void browser.runtime.sendMessage({type:'SCAN_URL',url:location.href}).then((state:unknown)=>show(state as ScanState,location.href)).catch(()=>undefined);
}
