import React,{useEffect,useRef,useState} from 'react';import {createRoot} from 'react-dom/client';import browser from 'webextension-polyfill';import L from 'leaflet';import 'leaflet.heat';import 'leaflet/dist/leaflet.css';import './bootstrap';import {Header,Notice} from './ui';import {settings} from './settings';import type {Alert} from './types';
interface Point {stateName:string;count:number;avgSeverity:number;lat:number;lng:number}
function Panel(){const[alerts,setAlerts]=useState<Alert[]>([]),[points,setPoints]=useState<Point[]>([]),[error,setError]=useState(''),[dashboard,setDashboard]=useState('');const container=useRef<HTMLDivElement>(null),map=useRef<L.Map>(),layers=useRef<L.Layer[]>([]);
 async function refresh(){try{const [feed,geo]=await Promise.all([browser.runtime.sendMessage({type:'GET_FEED'}),browser.runtime.sendMessage({type:'GET_HEATMAP'})]);setAlerts((feed as {alerts:Alert[]}).alerts);setPoints(geo as Point[]);setError('');}catch{setError('Intelligence is offline. Existing map data may be stale.');}}
 useEffect(()=>{void settings().then(value=>setDashboard(value.dashboardUrl));void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh();},30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!container.current)return;map.current=L.map(container.current,{center:[22.59,78.96],zoom:4,attributionControl:true});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{className:'dark-tiles',attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map.current);return()=>{map.current?.remove();map.current=undefined;};},[]);
 useEffect(()=>{const current=map.current;if(!current)return;layers.current.forEach(layer=>current.removeLayer(layer));layers.current=[];const valid=points.filter(point=>Number.isFinite(point.lat)&&Number.isFinite(point.lng));const max=Math.max(1,...valid.map(p=>p.count));const heat=(L as typeof L & {heatLayer:(points:number[][],options:Record<string,unknown>)=>L.Layer}).heatLayer(valid.map(point=>[point.lat,point.lng,point.count/max]),{radius:30,blur:22,gradient:{.3:'#06b6d4',.6:'#f59e0b',1:'#ef4444'}}).addTo(current);layers.current.push(heat);for(const point of valid){const text=document.createElement('span');text.textContent=point.stateName+': '+point.count+' incidents';const marker=L.circleMarker([point.lat,point.lng],{radius:Math.min(16,4+point.count),color:point.avgSeverity>=4?'#f87171':'#22d3ee',fillOpacity:.5}).bindTooltip(text).addTo(current);layers.current.push(marker);}},[points]);
 return <main className="min-w-[280px] space-y-4 p-4"><Header title="Shield intelligence"/>{error&&<Notice>{error}</Notice>}<button className="btn secondary w-full" onClick={()=>void refresh()}>Refresh intelligence</button><section className="card !p-0 overflow-hidden"><h2 className="p-4 text-sm font-semibold">Live India heatmap</h2><div ref={container} role="region" aria-label="India state incident heatmap"/><p className="muted p-3 text-[10px]">State centroids, not exact addresses · refreshes every 30 seconds while open.</p></section><h2 className="text-sm font-semibold">Recent incidents</h2>{alerts.length?alerts.map(alert=><a className="card block" key={alert.id} href={dashboard+'/incidents/'+alert.id} target="_blank" rel="noreferrer"><div className="flex justify-between gap-2 text-xs"><strong className="text-cyan-300">{alert.threatType.replaceAll('_',' ')}</strong><span className={alert.severity>=4?'text-red-300':'text-amber-200'}>Severity {alert.severity}</span></div><p className="muted mt-2">{alert.citizenExplanation||'Summary unavailable.'}</p><p className="mt-2 font-mono text-[10px] text-slate-400">{alert.geoTags?.join(', ')||'Location unavailable'} · {new Date(alert.createdAt).toLocaleDateString()}</p></a>):<p className="muted">{error?'Feed unavailable.':'No recent incidents.'}</p>}</main>;
}createRoot(document.getElementById('root')!).render(<Panel/>);
